#!/usr/bin/env python3
"""
Analyze and compare citation networks generated by different models.
This script compares PA, ER, and ER-GNP models.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
from collections import Counter
import seaborn as sns

# Set style
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (15, 10)

def load_network(edgelist_file):
    """Load network from edgelist file."""
    edges = pd.read_csv(edgelist_file, sep='\t', names=['source', 'target'], comment='#')
    G = nx.from_pandas_edgelist(edges, 'source', 'target', create_using=nx.DiGraph())
    return G

def compute_metrics(G, name):
    """Compute network metrics."""
    metrics = {
        'model': name,
        'num_nodes': G.number_of_nodes(),
        'num_edges': G.number_of_edges(),
        'density': nx.density(G),
        'avg_in_degree': np.mean([d for n, d in G.in_degree()]),
        'avg_out_degree': np.mean([d for n, d in G.out_degree()]),
    }
    
    # In-degree distribution statistics
    in_degrees = [d for n, d in G.in_degree()]
    metrics['max_in_degree'] = max(in_degrees)
    metrics['median_in_degree'] = np.median(in_degrees)
    metrics['std_in_degree'] = np.std(in_degrees)
    
    return metrics

def plot_degree_distributions(models_data):
    """Plot in-degree distributions for all models."""
    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    
    colors = ['#2E86AB', '#A23B72', '#F18F01']
    
    for idx, (name, G) in enumerate(models_data.items()):
        in_degrees = [d for n, d in G.in_degree()]
        out_degrees = [d for n, d in G.out_degree()]
        
        # In-degree histogram
        ax = axes[0, idx]
        ax.hist(in_degrees, bins=50, alpha=0.7, color=colors[idx], edgecolor='black')
        ax.set_xlabel('In-degree', fontsize=12)
        ax.set_ylabel('Frequency', fontsize=12)
        ax.set_title(f'{name} - In-degree Distribution', fontsize=14, fontweight='bold')
        ax.set_yscale('log')
        
        # Out-degree histogram
        ax = axes[1, idx]
        ax.hist(out_degrees, bins=50, alpha=0.7, color=colors[idx], edgecolor='black')
        ax.set_xlabel('Out-degree', fontsize=12)
        ax.set_ylabel('Frequency', fontsize=12)
        ax.set_title(f'{name} - Out-degree Distribution', fontsize=14, fontweight='bold')
    
    plt.tight_layout()
    plt.savefig('results/degree_distributions.png', dpi=300, bbox_inches='tight')
    print("Saved: results/degree_distributions.png")

def plot_degree_ccdf(models_data):
    """Plot complementary cumulative distribution function (CCDF) of in-degrees."""
    plt.figure(figsize=(10, 7))
    
    colors = ['#2E86AB', '#A23B72', '#F18F01']
    markers = ['o', 's', '^']
    
    for idx, (name, G) in enumerate(models_data.items()):
        in_degrees = sorted([d for n, d in G.in_degree()])
        degree_counts = Counter(in_degrees)
        
        degrees = sorted(degree_counts.keys())
        ccdf = []
        total = sum(degree_counts.values())
        
        for k in degrees:
            ccdf.append(sum(degree_counts[d] for d in degrees if d >= k) / total)
        
        plt.loglog(degrees, ccdf, marker=markers[idx], markersize=4, 
                   label=name, color=colors[idx], linewidth=2, alpha=0.7)
    
    plt.xlabel('In-degree (k)', fontsize=14)
    plt.ylabel('P(X ≥ k)', fontsize=14)
    plt.title('In-degree CCDF Comparison', fontsize=16, fontweight='bold')
    plt.legend(fontsize=12, loc='upper right')
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig('results/degree_ccdf.png', dpi=300, bbox_inches='tight')
    print("Saved: results/degree_ccdf.png")

def plot_metrics_comparison(metrics_df):
    """Plot bar chart comparing key metrics."""
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    metrics_to_plot = [
        ('num_edges', 'Number of Edges'),
        ('density', 'Network Density'),
        ('avg_in_degree', 'Average In-degree'),
        ('max_in_degree', 'Maximum In-degree')
    ]
    
    colors = ['#2E86AB', '#A23B72', '#F18F01']
    
    for idx, (metric, title) in enumerate(metrics_to_plot):
        ax = axes[idx // 2, idx % 2]
        bars = ax.bar(metrics_df['model'], metrics_df[metric], color=colors, alpha=0.8, edgecolor='black')
        ax.set_ylabel(title, fontsize=12)
        ax.set_title(title, fontsize=14, fontweight='bold')
        ax.grid(axis='y', alpha=0.3)
        
        # Add value labels on bars
        for bar in bars:
            height = bar.get_height()
            ax.text(bar.get_x() + bar.get_width()/2., height,
                   f'{height:.2f}' if metric == 'density' else f'{int(height)}',
                   ha='center', va='bottom', fontsize=10)
    
    plt.tight_layout()
    plt.savefig('results/metrics_comparison.png', dpi=300, bbox_inches='tight')
    print("Saved: results/metrics_comparison.png")

def main():
    print("=" * 60)
    print("Citation Network Analysis")
    print("=" * 60)
    
    # Load networks
    print("\nLoading networks...")
    models = {
        'PA': 'results/pa_network.txt',
        'ER Fixed-k': 'results/er_network.txt',
        'ER G(n,p)': 'results/er_gnp_network.txt'
    }
    
    models_data = {}
    for name, filepath in models.items():
        try:
            G = load_network(filepath)
            models_data[name] = G
            print(f"  ✓ Loaded {name}: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges")
        except FileNotFoundError:
            print(f"  ✗ Could not find {filepath}")
    
    if not models_data:
        print("\nError: No network files found. Run the simulation first!")
        return
    
    # Compute metrics
    print("\nComputing network metrics...")
    metrics_list = []
    for name, G in models_data.items():
        metrics = compute_metrics(G, name)
        metrics_list.append(metrics)
        print(f"\n{name}:")
        print(f"  Nodes: {metrics['num_nodes']}")
        print(f"  Edges: {metrics['num_edges']}")
        print(f"  Density: {metrics['density']:.6f}")
        print(f"  Avg in-degree: {metrics['avg_in_degree']:.2f}")
        print(f"  Max in-degree: {metrics['max_in_degree']}")
    
    metrics_df = pd.DataFrame(metrics_list)
    metrics_df.to_csv('results/network_metrics.csv', index=False)
    print("\nSaved: results/network_metrics.csv")
    
    # Generate plots
    print("\nGenerating visualizations...")
    plot_degree_distributions(models_data)
    plot_degree_ccdf(models_data)
    plot_metrics_comparison(metrics_df)
    
    print("\n" + "=" * 60)
    print("Analysis complete! Check the results/ directory for outputs.")
    print("=" * 60)

if __name__ == "__main__":
    main()
